apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    secureJsonData:
      httpHeaderValue1:  'Token $INFLUXDB_API_TOKEN'
    jsonData:
      dbName: k6
      httpMode: GET
      httpHeaderName1: 'Authorization'
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
