ingress:
  enabled: true
  host: localhost

redis:
  enabled: true
  image: redis:7
  port: 6379

accountService:
  image: account-service:0.0.1-SNAPSHOT
  replicas: 2
  db:
    host: account-db
    user: postgres
    password: postgres
  redis:
    host: redis
  kafka:
    bootstrapServers: kafka:9092
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

transactionService:
  image: transaction-service:0.0.1-SNAPSHOT
  replicas: 2
  db:
    host: transaction-db
    user: postgres
    password: postgres
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70
  accountService:
    url: http://account-service

postgres:
  image: postgres:17-alpine
  accountDb:
    name: account
    user: postgres
    password: postgres
  transactionDb:
    name: transaction
    user: postgres
    password: postgres

kafka:
  enabled: true
  image: wurstmeister/kafka:2.13-2.7.0
  replicas: 1

zookeeper:
  enabled: true
  image: zookeeper:3.5.8
  replicas: 1

# The liveness and readiness probes are used to only accept request when the service is fully started.
# Depending on the resource allocation, it may take 3 to 75 seconds to start the service.
probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    failureThreshold: 3
    initialDelaySeconds: 40
    periodSeconds: 20
    timeoutSeconds: 20
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    # When all instances become unready, the service will be unavailable and return 503.
    # So it should be cautious to set the failureThreshold.
    failureThreshold: 5
    initialDelaySeconds: 45
    periodSeconds: 5
    timeoutSeconds: 20

