ingress:
  enabled: true
  host: localhost
  timeout: 30s

redis:
  enabled: true
  image: redis:7-alpine
  port: 6379

nacos:
  global:
    storageClass: "standard"
  
  auth:
    enabled: false
  
  mode: standalone
  
  service:
    port: 8848
    
  persistence:
    enabled: true
    size: 1Gi
    
  resources:
    limits:
      cpu: 200m
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 1Gi

accountService:
  image: app-account-service:0.0.1-SNAPSHOT
  replicas: 1
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
  env:
    - name: DB_HOST
      value: account-db
    - name: DB_NAME
      value: account
    - name: SPRING_DATA_REDIS_HOST
      value: redis
    - name: SPRING_DATASOURCE_USERNAME
      value: postgres
    - name: SPRING_DATASOURCE_PASSWORD
      value: postgres
    - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
      value: "2000"
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: kafka:9092
    - name: SERVER_TOMCAT_THREADS_MAX
      value: "8"
    - name: BPL_JVM_THREAD_COUNT
      value: "100"
    - name: JAVA_OPTS
      value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Djava.rmi.server.hostname=127.0.0.1"
    - name: NACOS_HOST
      value: nacos
    - name: NACOS_PORT
      value: "8848"

transactionService:
  image: app-transaction-service:0.0.1-SNAPSHOT
  replicas: 1
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 60
  env:
    - name: SERVER_PORT
      value: "8080"
    - name: DB_HOST
      value: transaction-db
    - name: DB_NAME
      value: transaction
    - name: SPRING_DATASOURCE_USERNAME
      value: postgres
    - name: SPRING_DATASOURCE_PASSWORD
      value: postgres
    - name: SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT
      value: "2000"
    - name: SERVER_TOMCAT_THREADS_MAX
      value: "4"
    - name: BPL_JVM_THREAD_COUNT
      value: "100"
    - name: JAVA_OPTS
      value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Djava.rmi.server.hostname=127.0.0.1"
    - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
      value: kafka:9092
    - name: NACOS_HOST
      value: nacos
    - name: NACOS_PORT
      value: "8848"

postgres:
  image: postgres:17-alpine
  accountDb:
    enabled: true
    name: account
    user: postgres
    password: postgres
  transactionDb:
    enabled: true
    name: transaction
    user: postgres
    password: postgres

kafka:
  enabled: true
  image: wurstmeister/kafka:2.13-2.7.0
  replicas: 1

zookeeper:
  enabled: true
  image: zookeeper:3.5.8
  replicas: 1

# The liveness and readiness probes are used to only accept request when the service is fully started.
# Depending on the resource allocation, it may take 3 to 75 seconds to start the service.
probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    failureThreshold: 3
    successThreshold: 1
    initialDelaySeconds: 40
    periodSeconds: 20
    timeoutSeconds: 20
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    # When all instances become unready, the service will be unavailable and return 503.
    # So it should be cautious to set the failureThreshold.
    failureThreshold: 3
    successThreshold: 1
    initialDelaySeconds: 45
    periodSeconds: 5
    timeoutSeconds: 20

