ingress:
  enabled: true
  host: localhost

redis:
  enabled: true
  image: redis:7
  port: 6379

accountService:
  image: account-service:0.0.1-SNAPSHOT
  replicas: 2
  db:
    host: account-db
    user: postgres
    password: postgres
  redis:
    host: redis
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

transactionService:
  image: transaction-service:0.0.1-SNAPSHOT
  replicas: 2
  db:
    host: transaction-db
    user: postgres
    password: postgres
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 70

postgres:
  image: postgres:17-alpine
  accountDb:
    name: account
    user: postgres
    password: postgres
  transactionDb:
    name: transaction
    user: postgres
    password: postgres

probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    failureThreshold: 3
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 10
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    failureThreshold: 1
    initialDelaySeconds: 60
    periodSeconds: 5
    timeoutSeconds: 5

