accountService:
  image: account-service:0.0.1-SNAPSHOT
  replicas: 3
  db:
    host: account-db
    user: postgres
    password: postgres
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

transactionService:
  image: transaction-service:0.0.1-SNAPSHOT
  replicas: 3
  db:
    host: transaction-db
    user: postgres
    password: postgres
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50

postgres:
  image: postgres:17-alpine
  accountDb:
    name: account
    user: postgres
    password: postgres
  transactionDb:
    name: transaction
    user: postgres
    password: postgres

probes:
  liveness:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
  readiness:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10

