server:
  port: 8082

spring:
  application:
    name: real-balance-transaction

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:transaction}
    username: postgres
    password: postgres
  jpa:
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "io.github.hugogu.*"
  jackson:
    deserialization:
      fail-on-unknown-properties: false

account:
  service:
    url: http://localhost:8080/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
