server:
  port: 8080
  tomcat:
    threads:
      # The default value 200 is too high which would slow down the application.
      # TPS will increase from 250 to 400 by changing the value to around 8 to 16 (based on CPU cores).
      max: 8
    connection-timeout: 20s
    max-keep-alive-requests: 100

spring:
  application:
    name: real-balance-account
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:account}
    username: postgres
    password: postgres
    hikari:
      connection-timeout: 2000
  cache:
    type: redis
    redis:
      enable-statistics: true
  jpa:
    open-in-view: false
  task:
    scheduling:
      pool:
        size: 4
      simple:
        concurrency-limit: 8
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        transaction.timeout.ms: "5000"
        request.timeout.ms: "3000"
        delivery.timeout.ms: "10000"
        max.block.ms: "15000"
    consumer:
      group-id: ${spring.application.name}
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "io.github.hugogu.*"
      max-poll-records: 20
      # According to the nature of transaction message received from API.
      # There are lock and idempotent check in the service layer.
      # So, we don't need the transactional feature of Kafka itself.
      # Although the default is `read_uncommitted` already,
      # set it deliberately to avoid misunderstanding.
      isolation-level: read_uncommitted
    admin:
      # Topic automatic creation should finish in 10s.
      operation-timeout: 10s
    listener:
      type: single
  data:
    redis:
      host: localhost
      port: 6379

service:
  lock:
    timeout: 10s

kafka:
  topics:
    pending-transaction:
      partitions: 16
      replicas: 1

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-components: always
      show-details: always

logging:
  level:
    org:
      apache:
        kafka:
          clients:
            # Avoid unnecessary noice from Kafka client.
            NetworkClient: WARN
      hibernate:
        engine:
          jdbc:
            spi: WARN
      springframework:
        retry:
          support: INFO
