apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-db
  template:
    metadata:
      labels:
        app: account-db
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.accountDb.name }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.accountDb.user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.accountDb.password }}
          volumeMounts:
            - name: account-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: account-db-storage
          persistentVolumeClaim:
            claimName: account-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: account-db
spec:
  type: NodePort
  selector:
    app: account-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30007
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: account-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
