apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: real-balance-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Automatically retry requests that return a 503 and 502 status code.
    nginx.ingress.kubernetes.io/retry-on: "502,503"
    nginx.ingress.kubernetes.io/proxy-next-upstream: "error http_502 http_503"
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "10s"
    nginx.ingress.kubernetes.io/proxy-next-upstream-tries: "3"
    # For AWS or GCP
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /account.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: account-service
                port:
                  number: 8080
          # Expose actuator to access chaos monkey api for testing.
          - path: /actuator.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: account-service
                port:
                  number: 8080
          - path: /transaction.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
