{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: real-balance-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    # For AWS or GCP
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /account.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: account-service
                port:
                  number: 8080
          - path: /transaction.*
            pathType: ImplementationSpecific
            backend:
              service:
                name: transaction-service
                port:
                  number: 8080
{{- end }}
