apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
spec:
  replicas: {{ .Values.transactionService.replicas }}
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: {{ .Values.transactionService.image }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "128m"
            limits:
              memory: "1024Mi"
              cpu: "512m"
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: DB_HOST
              value: {{ .Values.transactionService.db.host }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.transactionService.db.user }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.transactionService.db.password }}
            - name: ACCOUNT_SERVICE_URL
              value: {{ .Values.transactionService.accountService.url }}
          livenessProbe: {{ toYaml .Values.probes.liveness | nindent 12 }}
          readinessProbe: {{ toYaml .Values.probes.readiness | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

{{- if .Values.transactionService.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: transaction-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: transaction-service
  minReplicas: {{ .Values.transactionService.hpa.minReplicas }}
  maxReplicas: {{ .Values.transactionService.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.transactionService.hpa.targetCPUUtilizationPercentage }}
{{- end }}
